"""add user status

Revision ID: 1ada86eebe4b
Revises: 
Create Date: 2020-08-03 16:56:06.817263

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '1ada86eebe4b'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('company', 'logo',
               existing_type=mysql.VARCHAR(length=128),
               nullable=False)
    op.drop_column('dilivery', 'status')
    op.add_column('user', sa.Column('is_disable', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'is_disable')
    op.add_column('dilivery', sa.Column('status', mysql.SMALLINT(display_width=6), autoincrement=False, nullable=True))
    op.alter_column('company', 'logo',
               existing_type=mysql.VARCHAR(length=128),
               nullable=True)
    # ### end Alembic commands ###
